### ISSUE TITLE
docker compose error message

### ISSUE THREAD

**Issue by coolpalani** [mateothegreat/docker-alpine-jenkins#3]
When I execute docker compose, it's throwing below error message.
`$ docker-compose up -d`
Creating network "dockeralpinejenkins_default" with the default driver
Pulling master (appsoa/docker-alpine-jenkins:1.0.0)...
ERROR: manifest for appsoa/docker-alpine-jenkins:1.0.0 not found

I believe you have to point this image to latest tag in the compose file

` image: 'appsoa/docker-alpine-jenkins:latest'` instead of  `image: 'appsoa/docker-alpine-jenkins:1.0.0'`

**Comment by mateothegreat** [comment]
@coolpalani you're right.. I double checked docker hub, I missed pushing that tag. docker-compose.yml has been updated. Thank you!!
